### ISSUE TITLE
Refactoring of Hi-C plotting

### ISSUE THREAD

**Issue by teunbrand** [teunbrand/ggnomics#22]
In an effort to make Hi-C matrix plotting more flexible, the following might be neat.

- [ ] Write new, general Hi-C matrix function #23 
- [ ] Reshape the `geom_hictriangle` as a position function #24 
- [ ] Add stat functions for Hi-C #25 
- [ ] Build facet function for annotations #26

**Comment by teunbrand** [comment]
I'll be postponing these untill I can get #32 to work, so I can express Hi-C matrices with genomic coordinates.
